# Site settings
title: Portal Inês Etienne Romeu
email: vicfermino@icloud.com
github_username:  vfermino
baseurl: "http://jornaleiros.com"
encoding: "utf-8"
excerpt_separator: <!--break-->
# Build settings
markdown: kramdown
permalink: none
paginate: 16
