# Site settings
title: Protótipo
email: vicfermino@icloud.com
github_username:  vfermino
base_url: "vfermino.github.io"
encoding: "utf-8"
authors:
  victor:
    name: Victor Fermino
    display_name: Victor Fermino
    description: "Desertor do curso de Análise e Desenvolvimento de Sistemas e atual estudante de Jornalismo, ambos na Universidade Metodista. Gosta de tecnologia, literatura e filmes. Possui um grande interesse por documentários e um vício em The Binding of Isaac e Super Meat Boy."
    email: vfermino@protonmail.ch
    web: http://cartapaulista.com.br
    github: vfermino

excerpt_separator: <!--break-->
# Build settings
markdown: kramdown
permalink: none
paginate: 5
