# Site settings
title: Protótipo
email: vicfermino@icloud.com
github_username:  vfermino
baseurl: "http://vfermino.github.io/portal-ca"
encoding: "utf-8"
excerpt_separator: <!--break-->
# Build settings
markdown: kramdown
permalink: none
paginate: 5
